# Site settings
title: MonetaVerde
subtitle: MonetaVerde - Building Green Cryptocurrency
email: info@monetaverde.io
description-title: Welcome to MonetaVerde Project!
description-detail: We are building Green Cryptocurrency
definition-title: What is MonetaVerde?
definition-detail: "Moneta Verde (it) means <b>green coin</b>: this coin uses already existing mining resources (MM) 
and it's supply is regulated by mining community. Moneta Verde is the first cryptocoin with blockreward increasing 
together with difficulty. Block reward formula is a fixed point implementation of log2(difficulty). 
This means that block reward increases much slower than difficulty: for 1 coin to be added to block 
reward a difficulty must be increased twice. The goal is decline in deflation. The less the deflation 
the more it is profitable to save up some MCN. Deflation ruins the usage of cryptocurrency as a legal tender."

# baseurl: "/jekyll-doc-theme" # the subpath of your site, e.g. /blog/
url: https://wiki.monetaverde.io # the base hostname & protocol for your site
# git_address: https://github.com/monetaverde
# git_edit_address: https://github.com/aksakalli/jekyll-doc-theme/blob/gh-pages

# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
# bootwatch: paper

# Social Media
login_url: https://login.monetaverde.io
twitter_url: https://twitter.com/monetaverde_mcn
github_url: https://github.com/monetaverde
linkedin_url: https://www.linkedin.com/company/monetaverde
telegram_url: https://t.me/monetaverdeofficial
medium_url: https://medium.com/@monetaverde
slack_url: https://monetaverde.slack.com
blog_url: https://blog.monetaverde.io
coinmarketcap_url: https://coinmarketcap.com/currencies/monetaverde
reddit_url: https://www.reddit.com/r/MonetaVerde
bitcointalk_url: https://bitcointalk.org/index.php?topic=657820.0

# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
timezone: Europe/Istanbul
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true
